name: Build and deploy documentation
on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@2.0.3
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: doc/dist
          BUILD_SCRIPT: npm install && npm run build && npm run generate
